import rdflib

auth = rdflib.Namespace("http://vocab.rpi.edu/auth/")
dc = rdflib.Namespace("http://purl.org/dc/terms/")
foaf = rdflib.Namespace("http://xmlns.com/foaf/0.1/")
frbr = rdflib.Namespace("http://purl.org/vocab/frbr/core#")
np = rdflib.Namespace("http://www.nanopub.org/nschema#")
prov = rdflib.Namespace("http://www.w3.org/ns/prov#")
pv = rdflib.Namespace("http://purl.org/net/provenance/ns#")
setl = rdflib.Namespace("http://purl.org/twc/vocab/setl/")
sio = rdflib.Namespace("http://semanticscience.org/resource/")
sioc = rdflib.Namespace("http://rdfs.org/sioc/ns#")
sioc_types = rdflib.Namespace("http://rdfs.org/sioc/types#")
skos = rdflib.Namespace("http://www.w3.org/2008/05/skos#")
whyis = rdflib.Namespace('http://vocab.rpi.edu/whyis/')
