#!/bin/bash

sudo apt-get update
sudo apt-get install python3-venv python3-dev
python3 -m venv .venv
source .venv/bin/activate
pip install requests wheel twine setuptools
sudo apt-get install -y software-properties-common \
			build-essential \
			aptitude
sudo apt-get install -y default-jdk-headless

sudo apt-get install -y npm 

