#!/bin/bash

# exit when any command fails
set -e

sudo apt-get update
sudo apt-get install -y software-properties-common

WHYIS_USER=`id -u -n`

WHYIS_HOME=${WHYIS_HOME:-/home/$WHYIS_USER}

FUSEKI_SERVER=`which fuseki-server`
FUSEKI_HOME=$PWD/fuseki
WHYIS_APP_HOME=$PWD

sudo apt-get install -y apache2-dev \
			unzip \
			zip \
			default-jdk \
			build-essential \
			automake libblas3 \
			libblas-dev \
			celery \
			redis-server \
			apache2 \
			libffi-dev \
			libssl-dev \
			maven \
			libdb5.3-dev \
			python3.7-dev

mkdir -p $WHYIS_APP_HOME/data/nanopublications
mkdir -p $WHYIS_APP_HOME/fuseki
mkdir -p $WHYIS_APP_HOME/data/files
mkdir -p $WHYIS_APP_HOME/celery

sudo chown -R $WHYIS_USER:$WHYIS_USER /var/log/celery

sudo mkdir -p /var/log/whyis
sudo chown -R $WHYIS_USER:$WHYIS_USER /var/log/whyis

# configure celery
sudo cat < $PWD/install_files/etc/default/celeryd \
	 > /etc/default/celeryd
sudo cat < $PWD/install_files/celerybeat.service \
         > /etc/systemd/system/celerybeat.service
sudo cat < $PWD/install_files/celery.service \
         > /etc/systemd/system/celery.service

# enable wsgi
sudo mod_wsgi-express module-config > /etc/apache2/mods-available/wsgi.load
sudo a2enmod wsgi
sudo a2enmod headers
sudo cat < $PWD/install_files/etc/apache2/sites-available/000-default.conf \
	 > /etc/apache2/sites-available/000-default.conf

# set up fuseki
sudo cat < $PWD/install_files/fuseki.service \
	 > /etc/systemd/system/fuseki.service

sudo systemctl enable fuseki.service

# start services
sudo service apache2 restart
sudo service celeryd restart
sudo service fuseki start

echo "Complete!"
